        aidl = true
    }

    // Make per-variant version code
    libraryVariants.all { variant ->
        //Custom APK name
        variant.outputs.each { output ->
            if (output.outputFileName != null && output.outputFileName.endsWith('.aar')) {
                output.outputFileName = "medialibrary-${abi}-${library_version}.aar"
            }
        }
    }
}

clean {
    delete 'build', 'jni/libs', 'jni/obj'
}

dependencies {
    if (project.findProject(':libvlcjni:libvlc') != null) {
        releaseImplementation project(':libvlcjni:libvlc')
        devImplementation project(':libvlcjni:libvlc')
    }
    debugImplementation "org.videolan.android:libvlc-all:$rootProject.ext.libvlcVersion"
    api "androidx.legacy:legacy-support-v4:$rootProject.ext.androidxLegacyVersion"
    api "androidx.core:core:$rootProject.ext.androidxCoreVersion"
    api "androidx.fragment:fragment:$rootProject.ext.androidxFragmentVersion"
    testImplementation "junit:junit:$rootProject.ext.junitVersion"
    testImplementation "org.robolectric:robolectric:4.3.1"
}

apply from: '../buildsystem/publish.gradle'